version: '3.8'

services:
  web:
    build: .
    command: python alikson_shop/manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/test_alikson
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: alikson_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
